name: Deploy Lambda Function with config

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    env: 
      AWS_ACCESS_var_ID: ${{ secrets.AWS_ACCESS_var_ID }}
      AWS_SECRET_ACCESS_var: ${{ secrets.AWS_SECRET_ACCESS_var }}
      AWS_DEFAULT_REGION: "ap-northeast-3"

    steps:
      - uses: actions/checkout@v2

      - name: Install zip tool
        uses: montudor/action-zip@v1

      - name: Create Zip file for Lambda function
        run: zip -r code.zip .

      - name: Deploy Lambda Code
        uses: imehedi/actions-awscli-v2@latest
        with:
          args: "lambda update-function-code 
                --function-name github-actions 
                --zip-file fileb://code.zip"

      - name: Update Lambda Configuration
        uses: imehedi/actions-awscli-v2@latest
        with:
          args: "lambda update-function-configuration 
                --function-name github-actions 
                --runtime nodejs22.x 
                --timeout 20
                --memory-size 512"

      - name: Add Environment Variables
        uses: imehedi/actions-awscli-v2@latest
        with:
          args: |
            lambda update-function-configuration 
            --function-name github-actions 
            --environment Variables={var1=value1,var2=value2}

      - name: Add SQS Trigger
        uses: imehedi/actions-awscli-v2@latest
        with:
          args: "lambda create-event-source-mapping 
              --function-name github-actions 
              --batch-size 10 
              --event-source-arn arn:aws:sqs:ap-northeast-3:569917129798:githubActions"
