name: Deploy Lambda Function with SQS Trigger

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    env: 
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_DEFAULT_REGION: "ap-northeast-3"

    steps:
      - uses: actions/checkout@v2

      - name: Install zip tool
        uses: montudor/action-zip@v1

      - name: Create Zip file for Lambda function
        run: zip -r code.zip .

      - name: Deploy Lambda Code
        uses: imehedi/actions-awscli-v2@latest
        with:
          args: "lambda update-function-code --function-name github-actions --zip-file fileb://code.zip"

      - name: Update Lambda Configuration
        uses: imehedi/actions-awscli-v2@latest
        with:
          args: "lambda update-function-configuration --function-name github-actions --runtime nodejs18.x --timeout 30 --memory-size 256"