name: Deploy Multiple Lambda Functions

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    env: 
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_DEFAULT_REGION: "ap-northeast-3"

    steps:
      - uses: actions/checkout@v2

      - name: Install zip tool
        uses: montudor/action-zip@v1

      - name: Install AWS CLI
        run: |
          sudo apt-get update
          sudo apt-get install -y awscli

      - name: Deploy Lambda Functions
        run: |
          for dir in $(find ./lambdas -mindepth 1 -maxdepth 1 -type d); do
            # Get function name from folder
            FUNCTION_NAME=$(basename "$dir")
            echo "Deploying $FUNCTION_NAME"

            # Create ZIP file for the Lambda function
            cd "$dir"
            zip -r ../"${FUNCTION_NAME}.zip" .
            cd ..

            # Deploy the code
            aws lambda update-function-code \
              --function-name "${FUNCTION_NAME}" \
              --zip-file "fileb://${FUNCTION_NAME}.zip"

            # Update configuration
            aws lambda update-function-configuration \
              --function-name "${FUNCTION_NAME}" \
              --runtime "nodejs22.x" \
              --timeout 20 \
              --memory-size 512 \
              --environment "Variables={var1=value1,var2=value2}"

            # Add SQS Trigger (if needed)
            if [ "${FUNCTION_NAME}" = "github-actions" ]; then
              aws lambda create-event-source-mapping \
                --function-name "${FUNCTION_NAME}" \
                --batch-size 10 \
                --event-source-arn "arn:aws:sqs:ap-northeast-3:569917129798:githubActions"
            fi
          done
