name: Deploy Multiple Lambda Functions

on:
  push:
    branches: [ '*' ]  # Trigger on all branches

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: github.ref != 'refs/heads/main'  # Skip for main branch

    env: 
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_DEFAULT_REGION: "ap-northeast-3"

    steps:
      - uses: actions/checkout@v2

      - name: Install zip tool
        run: sudo apt-get install -y zip

      - name: Install or Update AWS CLI
        run: |
          curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
          unzip awscliv2.zip
          sudo ./aws/install --update

      - name: Deploy Lambda Functions
        run: |
            MAX_RETRIES=5
            RETRY_DELAY=15
            TENANT_ID=$(echo "${{ github.ref_name }}" | tr -cd '[:alnum:]' | tr '[:upper:]' '[:lower:]')
            ROLE_NAME="LambdaRole_${TENANT_ID}"

            # Function to create IAM role if not exists
            create_iam_role() {
              ROLE_EXISTS=$(aws iam get-role --role-name "$ROLE_NAME" --query 'Role.RoleName' --output text 2>/dev/null || echo "NO")

              if [ "$ROLE_EXISTS" = "NO" ]; then
                echo "Creating IAM role $ROLE_NAME..."
                aws iam create-role --role-name "$ROLE_NAME" \
                  --assume-role-policy-document '{
                    "Version": "2012-10-17",
                    "Statement": [{
                      "Effect": "Allow",
                      "Principal": {"Service": "lambda.amazonaws.com"},
                      "Action": "sts:AssumeRole"
                    }]
                  }'

                aws iam attach-role-policy --role-name "$ROLE_NAME" \
                  --policy-arn "arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole"
                aws iam attach-role-policy --role-name "$ROLE_NAME" \
                  --policy-arn "arn:aws:iam::aws:policy/AmazonSQSFullAccess"
                sleep 10
              else
                echo "IAM role $ROLE_NAME already exists."
              fi
            }

            for dir in ./lambdaFunctions/*/; do
              CONFIG_FILE="${dir}config.json"

              # Get base function configuration
              BASE_FUNCTION_NAME=$(jq -r '.functionName' "$CONFIG_FILE")
              RUNTIME=$(jq -r '.runtime' "$CONFIG_FILE")
              TIMEOUT=$(jq -r '.timeout' "$CONFIG_FILE")
              MEMORY_SIZE=$(jq -r '.memorySize' "$CONFIG_FILE")
              ENV_VARS=$(jq -r '.environmentVariables | to_entries | map("\(.key)=\(.value)") | join(",")' "$CONFIG_FILE")
              SQS_ENABLED=$(jq -r '.sqsTrigger.enabled' "$CONFIG_FILE")

              # Create tenant-specific function name
              FUNCTION_NAME="${TENANT_ID}_${BASE_FUNCTION_NAME}"
              echo "Deploying $FUNCTION_NAME"

              # Create a zip package excluding config.json
              zip -r "${FUNCTION_NAME}.zip" "${dir}" -x "${dir}config.json"

              FUNCTION_EXISTS=$(aws lambda get-function --function-name "$FUNCTION_NAME" --query 'Configuration.FunctionName' --output text 2>/dev/null || echo "NO")

              if [ "$FUNCTION_EXISTS" = "NO" ]; then
                echo "Creating new Lambda function $FUNCTION_NAME..."
                create_iam_role

                aws lambda create-function \
                  --function-name "$FUNCTION_NAME" \
                  --runtime "$RUNTIME" \
                  --role "arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/$ROLE_NAME" \
                  --handler "${dir}handler.lambda_handler" \
                  --timeout "$TIMEOUT" \
                  --memory-size "$MEMORY_SIZE" \
                  --environment "Variables={$ENV_VARS}" \
                  --zip-file "fileb://${FUNCTION_NAME}.zip" \
                  --tags "Tenant=$TENANT_ID"
              else
                echo "Updating existing Lambda function $FUNCTION_NAME..."
                aws lambda update-function-code --function-name "$FUNCTION_NAME" --zip-file "fileb://${FUNCTION_NAME}.zip"

                RETRY_COUNT=0
                while [ $RETRY_COUNT -lt $MAX_RETRIES ]; do
                  aws lambda update-function-configuration --function-name "$FUNCTION_NAME" --environment "Variables={$ENV_VARS}" && break
                  RETRY_COUNT=$((RETRY_COUNT+1))
                  echo "Update conflict detected for $FUNCTION_NAME. Retrying in $RETRY_DELAY seconds... ($RETRY_COUNT/$MAX_RETRIES)"
                  sleep $RETRY_DELAY
                done
                if [ $RETRY_COUNT -eq $MAX_RETRIES ]; then
                  echo "Failed to update function configuration for $FUNCTION_NAME after $MAX_RETRIES attempts."
                  exit 1
                fi
              fi

              if [ "$SQS_ENABLED" = "true" ]; then
                # Get base queue ARN and create tenant-specific queue ARN
                BASE_QUEUE_ARN=$(jq -r '.sqsTrigger.eventSourceArn' "$CONFIG_FILE")
                TENANT_QUEUE_ARN="${BASE_QUEUE_ARN%.*}_${TENANT_ID}.fifo"  # Assuming FIFO queues
                BATCH_SIZE=$(jq -r '.sqsTrigger.batchSize' "$CONFIG_FILE")
                
                EXISTING_MAPPING=$(aws lambda list-event-source-mappings --function-name "$FUNCTION_NAME" --query 'EventSourceMappings[?EventSourceArn==`'$TENANT_QUEUE_ARN'`].UUID' --output text)
                if [ -z "$EXISTING_MAPPING" ]; then
                  echo "Adding SQS trigger for $FUNCTION_NAME..."
                  aws lambda create-event-source-mapping --function-name "$FUNCTION_NAME" --batch-size "$BATCH_SIZE" --event-source-arn "$TENANT_QUEUE_ARN"
                else
                  echo "SQS trigger already exists for $FUNCTION_NAME. Skipping..."
                fi
              fi

              echo "Deployment complete for $FUNCTION_NAME."
              echo "Waiting 10 seconds before deploying the next function..."
              sleep 10
            done